resources:
- ../base
configMapGenerator:
  - name: environment
    behavior: merge
    files:
      - values.yaml=configmap.yaml
patches:
## Enable the section below if a secrets.enc.yaml is created in this directory
# - path: secrets.enc.yaml
#   target:
#     version: v1
#     kind: Secret
#     name: environment-bb
- patch: |-
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: bigbang
    spec:
      interval: 1m
# Use the following three lines to test a new version of Big Bang without affecting other environments
#    ref:
#      $patch: replace
#      tag: "2.27.0"
- patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta2
    kind: HelmRelease
    metadata:
      name: bigbang
    spec:
      interval: 1m
